build:
  only:
    refs:
      - tags
  image: docker:19.03.12
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG